### ISSUE TITLE
parse rx and tx bytes

### ISSUE THREAD

**Issue by kellyjonbrazil** [KnightWhoSayNi/ifconfig-parser#2]
Hi - I'm using `ifconfig-parser` in my `jc` project (https://github.com/kellyjonbrazil/jc) and I was wondering if we could add the rx and tx bytes in the `get_interfaces()` output.

**Comment by KnightWhoSayNi** [comment]
Yes, we could add support for total number of transmitted/received bytes over interfaces (if reported).
Can you share raw outputs so we can improve and test parsing (**remember to obfuscate your ip and mac address**)?

**Comment by kellyjonbrazil** [comment]
Thanks - here are the ifconfig outputs from centos 7.7 and ubuntu 18.4.
[ifconfig-centos.txt](https://github.com/KnightWhoSayNi/ifconfig-parser/files/3898060/ifconfig-centos.txt)
[ifconfig-ubuntu.txt](https://github.com/KnightWhoSayNi/ifconfig-parser/files/3898061/ifconfig-ubuntu.txt)

**Comment by KnightWhoSayNi** [comment]
I released the new version v0.0.5 with new attributes (**rx_bytes** and **tx_bytes**) for storing the total number of received/transmitted bytes over interfaces (if reported). 
Can you try it out and let me know if it works correctly?

**Comment by kellyjonbrazil** [comment]
Working great, thanks!
